### ISSUE TITLE
delete merged branches

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4_projects_libs#15]
There are a lot of branches that look as if the work has been merged. Could you remove them here?
* `missing-lincenses`
* `spdx`
* `spdx-syntax`
* `alyons-ppi`
* `kent/fix-style`
* `kent/rockpro64`
* `kent/remove-warning`
* `nomadeel/fdt-fix`

**Comment by lsf37** [comment]
Thanks for checking. It looks like someone has done this already, at least I can't see them any more. @axel-h can you confirm and close?

**Comment by axel-h** [comment]
sorry, seems this ended up in the wrong repo, should have been https://github.com/seL4/util_libs
